# Generated by Django 2.2 on 2020-08-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0002_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(default='download.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.ImageField(default='download.png', upload_to='images/'),
        ),
    ]
