# Generated by Django 3.0.6 on 2020-06-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
