# Generated by Django 3.0.6 on 2020-06-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200618_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='day',
            new_name='date',
        ),
    ]
