# Generated by Django 2.2 on 2020-08-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_news_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(default=None, max_length=3000)),
                ('url', models.CharField(max_length=500)),
                ('date', models.IntegerField(default=12)),
                ('month', models.CharField(default='june', max_length=50)),
                ('year', models.IntegerField(default=2020)),
                ('file', models.FileField(upload_to='files/')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('has_url', models.BooleanField(default=True)),
                ('has_file', models.BooleanField(default=True)),
                ('has_image', models.BooleanField(default=False)),
            ],
        ),
    ]
