# Generated by Django 3.0.8 on 2020-07-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=70)),
                ('pdf', models.FileField(blank=True, upload_to='files/')),
                ('link', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
