# Generated by Django 3.0.8 on 2020-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
