# Generated by Django 3.0.8 on 2020-07-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20200716_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
