# Generated by Django 3.0.8 on 2020-07-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_publication_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='has_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
