# Generated by Django 3.0.8 on 2020-07-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_auto_20200716_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='admin_approved',
        ),
    ]
