# Generated by Django 3.0.8 on 2020-07-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='body',
            field=models.CharField(default=None, max_length=5000),
        ),
    ]
