# Generated by Django 3.0.6 on 2020-07-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20200618_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='phone',
        ),
        migrations.AlterField(
            model_name='team',
            name='information',
            field=models.TextField(max_length=1500),
        ),
    ]
