# Generated by Django 3.0.6 on 2020-07-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20200709_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='designation',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
