# Generated by Django 2.2 on 2020-08-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20200801_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.CharField(blank=True, default='HSS', max_length=1500),
        ),
        migrations.AlterField(
            model_name='team',
            name='institute_name',
            field=models.CharField(blank=True, default='IITG', max_length=1500),
        ),
    ]
